# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-07-11 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=40)),
                ('b_address', models.CharField(max_length=20)),
                ('emp_age', models.CharField(max_length=20)),
                ('emp_height', models.CharField(max_length=20)),
                ('emp_weight', models.CharField(max_length=20)),
            ],
        ),
    ]
