# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-07-14 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0003_auto_20220714_1010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Values1',
            new_name='Values',
        ),
    ]
