# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-07-14 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0004_auto_20220714_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node1',
            fields=[
                ('node_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Node2',
            fields=[
                ('node_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Node3',
            fields=[
                ('node_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=40)),
            ],
        ),
    ]
