# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-07-19 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0006_auto_20220719_0910'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node1',
            fields=[
                ('node_id', models.IntegerField(primary_key=True, serialize=False)),
                ('b_address', models.CharField(max_length=20)),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Node2',
            fields=[
                ('node_id', models.IntegerField(primary_key=True, serialize=False)),
                ('b_address', models.CharField(max_length=20)),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Node3',
            fields=[
                ('node_id', models.IntegerField(primary_key=True, serialize=False)),
                ('b_address', models.CharField(max_length=20)),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Node4',
            fields=[
                ('node_id', models.IntegerField(primary_key=True, serialize=False)),
                ('b_address', models.CharField(max_length=20)),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='Node10',
        ),
        migrations.DeleteModel(
            name='Node20',
        ),
        migrations.DeleteModel(
            name='Node30',
        ),
        migrations.DeleteModel(
            name='Node40',
        ),
    ]
