# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2022-07-19 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0009_auto_20220719_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_given_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=40)),
                ('b_address', models.CharField(max_length=20)),
                ('emp_age', models.CharField(max_length=20)),
                ('emp_height', models.CharField(max_length=20)),
                ('emp_weight', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
