# Generated by Django 3.2 on 2023-03-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0011_auto_20220719_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=200, unique=True)),
                ('Address', models.CharField(max_length=200)),
                ('Username', models.CharField(max_length=200, unique=True)),
                ('Password', models.CharField(max_length=200)),
                ('Interests', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Driver_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=200, unique=True)),
                ('Address', models.CharField(max_length=200)),
                ('Username', models.CharField(max_length=200, unique=True)),
                ('Password', models.CharField(max_length=200)),
                ('Interests', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Place_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Latitude', models.CharField(max_length=200)),
                ('Longitude', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='Node1',
        ),
        migrations.DeleteModel(
            name='Node2',
        ),
        migrations.DeleteModel(
            name='Node3',
        ),
        migrations.DeleteModel(
            name='Node4',
        ),
        migrations.DeleteModel(
            name='Values',
        ),
    ]
