# Generated by Django 3.2 on 2023-03-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0013_auto_20230307_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_reg',
            name='Vehicle_number',
            field=models.CharField(default='', max_length=200),
        ),
    ]
