# Generated by Django 3.2 on 2023-03-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0014_driver_reg_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver_reg',
            name='Seat',
            field=models.CharField(default='4', max_length=200),
        ),
    ]
