# Generated by Django 3.2 on 2023-03-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0015_driver_reg_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver_reg',
            name='Status',
            field=models.CharField(default='Not approved', max_length=200),
        ),
    ]
