# Generated by Django 3.2 on 2023-03-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0016_alter_driver_reg_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stops_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tid', models.CharField(max_length=200)),
                ('Sname', models.CharField(max_length=200)),
                ('Time', models.CharField(max_length=200)),
                ('Latitude', models.CharField(max_length=200)),
                ('Longitude', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trip_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Date', models.CharField(max_length=200)),
                ('Uname', models.CharField(max_length=200)),
            ],
        ),
    ]
