# Generated by Django 3.2 on 2023-03-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0017_stops_table_trip_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_table',
            name='Name',
            field=models.CharField(max_length=200),
        ),
    ]
