# Generated by Django 3.2 on 2023-03-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0018_alter_trip_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_table',
            name='Userid',
            field=models.CharField(default='', max_length=200),
        ),
    ]
