# Generated by Django 3.2 on 2023-03-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0019_trip_table_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Trip_id', models.CharField(max_length=200)),
                ('Date', models.CharField(default='', max_length=200)),
                ('Tripname', models.CharField(max_length=200)),
                ('Source', models.CharField(max_length=200)),
                ('Stime', models.CharField(max_length=200)),
                ('Destination', models.CharField(max_length=200)),
                ('Dtime', models.CharField(default='', max_length=200)),
                ('Vehicle_name', models.CharField(default='', max_length=200)),
                ('Drivername', models.CharField(default='', max_length=200)),
                ('Contact', models.CharField(default='', max_length=200)),
                ('Passenger', models.CharField(default='4', max_length=200)),
                ('Puname', models.CharField(default='', max_length=200)),
                ('Duname', models.CharField(default='', max_length=200)),
                ('Status', models.CharField(default='Not accepted', max_length=200)),
                ('Payment', models.CharField(default='Not completed', max_length=200)),
                ('Distance', models.CharField(default='', max_length=200)),
                ('Amount', models.CharField(default='', max_length=200)),
                ('Dlat', models.CharField(default='', max_length=200)),
                ('Dlong', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
