# Generated by Django 3.2 on 2023-03-09 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0021_auto_20230309_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_table',
            name='Seat',
            field=models.CharField(default='', max_length=200),
        ),
    ]
