# Generated by Django 3.2 on 2023-03-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0022_trip_table_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_table',
            name='Seat',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
