# Generated by Django 3.2 on 2023-03-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0024_booking_table_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='Rating',
            field=models.CharField(default='', max_length=200),
        ),
    ]
