# Generated by Django 3.2 on 2023-03-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0025_alter_booking_table_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_table',
            name='Rating',
        ),
        migrations.AddField(
            model_name='booking_table',
            name='DRating',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AddField(
            model_name='booking_table',
            name='PRating',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
