# Generated by Django 3.2 on 2023-03-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0026_auto_20230309_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver_reg',
            old_name='Rating',
            new_name='Dlat',
        ),
        migrations.AddField(
            model_name='driver_reg',
            name='Dlong',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
