# Generated by Django 3.2 on 2023-03-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0027_auto_20230309_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('From', models.CharField(max_length=250)),
                ('To', models.CharField(max_length=300)),
                ('chat', models.CharField(max_length=300)),
            ],
        ),
    ]
