# Generated by Django 3.2 on 2023-03-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0030_chat_table_sts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_table',
            name='Userid',
            field=models.CharField(default='10846', max_length=200),
        ),
    ]
