# Generated by Django 3.2 on 2023-04-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0031_alter_trip_table_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer_reg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Phone', models.CharField(max_length=200, unique=True)),
                ('Address', models.CharField(max_length=200)),
                ('Username', models.CharField(max_length=200, unique=True)),
                ('Password', models.CharField(max_length=200)),
            ],
        ),
    ]
