# Generated by Django 3.2 on 2023-04-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0032_volunteer_reg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waste_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uname', models.CharField(max_length=200)),
                ('Latitude', models.CharField(max_length=200)),
                ('Longitude', models.CharField(max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('Vstatus', models.CharField(default='Not accepted', max_length=200)),
                ('Reqstatus', models.CharField(default='Nil', max_length=200)),
                ('Image_path', models.CharField(max_length=200)),
                ('Waste_types', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
