# Generated by Django 3.2 on 2023-04-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0033_waste_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste_table',
            name='Date',
            field=models.CharField(default='', max_length=200),
        ),
    ]
