# Generated by Django 3.2 on 2023-04-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0034_waste_table_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='waste_table',
            name='Vuname',
            field=models.CharField(default='', max_length=200),
        ),
    ]
