# Generated by Django 3.2 on 2023-04-10 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PID_app', '0037_auto_20230408_1021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking_table',
        ),
        migrations.DeleteModel(
            name='Driver_reg',
        ),
        migrations.DeleteModel(
            name='Place_table',
        ),
        migrations.DeleteModel(
            name='Stops_table',
        ),
        migrations.DeleteModel(
            name='Trip_table',
        ),
    ]
